dist: xenial
language: ruby
env:
  global:
    - TEXLIVE_PATH=$TRAVIS_BUILD_DIR/vendor/texlive
    - PATH=$TEXLIVE_PATH/bin/x86_64-linux:$PATH
    # We should have ~2 cores on a vm
    - MULTIPLY_PROCESSES=2
    - N=1
    - ONLY_GROUP=1,2
  matrix:
    # ConTeXt run is split because of long runtime
    - FLAVOUR=context N=4 ONLY_GROUP=1,2
    - FLAVOUR=context N=4 ONLY_GROUP=3,4
    - FLAVOUR=context N=4 ONLY_GROUP=5,6
    - FLAVOUR=context N=4 ONLY_GROUP=7,8
    - FLAVOUR=latex
    - FLAVOUR=xelatex
    - FLAVOUR=pdflatex
    - FLAVOUR=lualatex
    - FLAVOUR=tex
    - FLAVOUR=xetex
    - FLAVOUR=pdftex
    - FLAVOUR=luatex
cache:
  bundler: true
  directories:
    - $TEXLIVE_PATH
install:
  # NOTE: this is the default `bundle install` command
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
  # texlive.packages: oberdiek -> atbegshi, ms -> everyshi, graphics -> graphicx
  - TEXLIVE_INSTALL_PREFIX=$TEXLIVE_PATH ./travis/texlive.install
script: 
  - SKIP_PDF=true bundle exec rake install
  - bundle exec parallel_cucumber --serialize-stdout --multiply-processes $MULTIPLY_PROCESSES -n $N --only-group $ONLY_GROUP -- features
branches:
  only:
  - master
