(TeX-add-style-hook
 "tikzlibrarykodi.mitra.code"
 (lambda ()
   (TeX-add-symbols
    "kDMitra"
    "kDMitraFetchMatrixThen"
    "kDMitraParseMatrixTableThen"
    "kDMitraParseTable"
    "kDMitraParseAllRowsThen"
    "kDMitraParseOneRowThen"
    "kDMitraParseAllColsThen"
    "kDExit"
    "kDMitraParseRowEndThen"
    "kDMitraFetchRowEndThen"
    "kDMitraPrintRowEndThen"
    "kDMitraMaybeFetchRowOptionsThen"
    "kDMitraFetchRowOptionsThen"
    "kDMitraParseOneColThen"
    "kDMitraParseColEndThen"
    "kDMitraMaybeFetchColOptionsThen"
    "kDMitraFetchColOptionsThen"
    "kDMitraMaybePrintColEndThen"
    "kDMitraParseCellThen"
    "kDMitraMaybeFetchCellOptionsThen"
    "kDMitraFetchCellOptionsThen"
    "kDMitraFetchCellContentThen"
    "kDMitraMaybeDoCellThen"
    "kDMitraPrintCellThen"
    "kDMitraMaybeDumpCell"
    "kDMitraOutput"))
 :plain-tex)

